name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  statuses: write  # Memberikan izin untuk update status commit

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Build Jekyll Site
        uses: actions/jekyll-build-pages@v1
        with:
          source: .
          destination: ./_site

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  report-build-status:
    runs-on: ubuntu-latest
    needs: build
    if: success()  # Hanya berjalan jika build sukses
    permissions:
      statuses: write  # Memberikan izin update status commit
    steps:
      - name: Report Build Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}  # Pastikan token tersedia
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            const run_id = context.runId;
            const sha = context.sha;  // Menggunakan SHA terbaru

            github.rest.repos.createCommitStatus({
              owner,
              repo,
              sha,
              state: "success",
              target_url: `https://github.com/${owner}/${repo}/actions/runs/${run_id}`,
              description: "Build completed successfully!",
              context: "Build Status"
            });

  deploy:
    runs-on: ubuntu-latest
    needs: report-build-status
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
